# Generated by Django 3.2.8 on 2021-10-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bookingmodel_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
