# Generated by Django 3.2.8 on 2021-10-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookingmodel_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='is_completed',
        ),
    ]
