# Generated by Django 3.2.8 on 2021-10-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211029_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app.ordermodel'),
            preserve_default=False,
        ),
    ]
