# Generated by Django 3.2.8 on 2021-10-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('app', '0007_orderitemmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_owner', to='authentication.customermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_owner', to='authentication.customermodel'),
        ),
    ]
